MODEL:
  BERT_CKPT: "hfl/chinese-macbert-base"
  DEVICE: "cuda"
  NAME: "macbert4csc"
  GPU_IDS: [0]
  HYPER_PARAMS: [0.3]
  WEIGHTS: ""

DATASETS:
  TRAIN: "../data/sighan_2015/train.json"
  VALID: "../data/sighan_2015/test.json"
  TEST: "../data/sighan_2015/test.json"

SOLVER:
  BASE_LR: 5e-5
  WEIGHT_DECAY: 0.01
  BATCH_SIZE: 32
  MAX_EPOCHS: 10
  ACCUMULATE_GRAD_BATCHES: 4

OUTPUT_DIR: "outputs-macbert4csc"
MODE: ["train", "test"]
